name: 'csds397_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'csds397_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  csds397_dbt_project:
    # Default materialization method for all models in this project
    + materialized: table

    # Override for staging models
    staging:
      + materialized: view
      + docs:
        node_color: 'silver'
    
    # Project-wide docmentation settings
    + docs:
        node_color: 'gold'

# Configuring seeds
seeds:
  csds397_dbt_project:
    employee_data_clean:
      +column_types:
        Employee_Id: integer
        Name: varchar(60)
        Age: integer
        Department: varchar(20)
        Date_of_Joining: date
        Years_of_Experience: integer
        Country: varchar(20)
        Salary: integer
        Performance_Rating: varchar(20)
