version: 2

models:
  - name: stg_employee_data
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null
      - name: employee_name
        tests:
          - not_null
      - name: age
        tests:
          - not_null
      - name: department
        tests:
          - not_null
          - accepted_values:
              values: ["Operations", "Customer Support", "HR", "IT", "Logistics", "Legal", "Marketing", "Sales", "Finance", "R&D"]
      - name: date_of_joining
        tests:
          - not_null
      - name: years_experience
        tests:
          - not_null
      - name: country
        tests:
          - not_null
      - name: salary
        tests:
          - not_null
      - name: performance_rating
        tests:
          - not_null
